### ISSUE TITLE
Accessing clientside class in serverside jar

### ISSUE THREAD

**Issue by yrsegal** [StoryOfLife/StoryOfLife#8]
https://pastebin.com/H6fheHqK

There's a few solutions:

* You can clientside [this class](https://github.com/StoryOfLife/StoryOfLife/blob/master/src/main/java/net/nolifers/storyoflife/util/PathDebugger.java#L21)
* You can only [subscribe](https://github.com/StoryOfLife/StoryOfLife/blob/master/src/main/java/net/nolifers/storyoflife/util/PathDebugger.java#L20) on the clientside
* You can clientside [this method](https://github.com/StoryOfLife/StoryOfLife/blob/master/src/main/java/net/nolifers/storyoflife/util/PathDebugger.java#L38) ***(recommended solution)***

**Comment by veesusmikelheir** [comment]
Man that's weird, I would've thought forge would recognize it being a clientside only event. 
Sorry for getting back to you so late, I'll fix it right away.

**Comment by yrsegal** [comment]
Forge can't do anything like that. The only time anything gets removed by Forge is when it (or its superclass, in the case of classes) is annotated with @SideOnly.
